version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  kds-consumer:
    image: kinesis-resurface-consumer
    container_name: kds-resurface-consumer
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2